name: '63 - Froala - CTA Block Right Title, Description With Background'
multiple: FALSE
category: 'Call to action'
enabled: TRUE
fields:
  title:
    type: text
    label: 'Titre'
    options:
      '#required': TRUE
  description:
    type: textarea
    label: 'Description'
    options:
      '#required': TRUE
  link:
    type: url_extended
    label: 'Lien'
