vactory_notifications.settings:
  type: config_object
  mapping:
    notifications_default_title:
      type: text
      label: 'Notifications default title'
    notifications_default_message:
      type: text
      label: 'Notifications default message'
    mail_default_subject:
      type: text
      label: 'Mail default title'
    mail_default_message:
      type: text
      label: 'Mail default message'
    langcode:
      type: string
      label: 'Language code'
