name: 'Three Columns'
multiple: FALSE
category: 'Job Ads'
enabled: TRUE
fields:
  title:
    type: text
    label: "Titre"
  description:
    type: text_format
    label: 'Description'
    options:
      '#format': 'basic_html'
  views:
    type: dynamic_views
    label: 'Views'
    options:
      '#required': TRUE
      '#default_value':
        views_id: vactory_job_ads
        views_display_id: block_three_columns
        fields:
          id: id
          uuid: key
          title: title
          url: url
          created: created
          field_vactory_description: profileDescription
          field_vactory_city: city
          field_vactory_contract: contract
          field_vactory_profession: profession
  link:
    type: url_extended
    label: 'Lien'
