name: 'Job Application'
multiple: FALSE
category: 'Job Ads'
enabled: TRUE
fields:
  webform:
    type: webform_decoupled
    label: 'Formulaire'
    options:
      '#required': TRUE
      '#default_value':
        webform_id: vactory_job_application
extra_fields:
  title:
    type: text
    label: "Titre"
  intro:
    type: text_format
    label: 'Introduction'
    options:
      '#format': 'full_html'
  link:
    type: url_extended
    label: 'Lien'
