name: 'D32 - Team V4'
multiple: TRUE
category: 'Teams'
enabled: TRUE
fields:
  image:
    type: image
    label: 'Image Profile'
    options:
      '#required': TRUE
  image_alt:
      type: text
      label: 'Text alternatif'
  name:
    type: text
    label: 'Name'
    options:
      '#required': TRUE
  role:
    type: text
    label: 'Role'
  linkedin:
    type: text
    label: 'Linkedin profile'
  twitter:
    type: text
    label: 'Twitter profile'
  youtube:
    type: text
    label: 'Youtube profile'
extra_fields:
  intro:
    type: textarea
    lable: 'Introduction'
  btn_more:
    type: url_extended
    label: 'More button'
