name: '83 - Froala - Features 2 Blocks Large Title, Description & CTA'
multiple: TRUE
category: 'Froala'
enabled: TRUE
limit: 2
fields:
  title:
    type: text
    label: 'Titre'
  description:
    type: text_format
    label: 'Description'
    options:
      '#format': 'full_html'
  link:
    type: url_extended
    label: 'Lien'
extra_fields:
  title:
    type: text
    label: 'Titre'
  intro:
    type: textarea
    label: 'Introduction'
  image:
    type: image
    label: 'Image'
  image_alt:
    type: text
    label: 'Text alternatif'
