name: 'D07 - List Cards With Picto'
multiple: TRUE
category: 'Content'
enabled: TRUE
fields:
  title:
    type: text
    label: 'Title'
    options:
      '#required': TRUE
  description:
    type: textarea
    label: 'Description'
  link:
    type: url_extended
    label: 'Lien du bouton'
  image:
    type: image
    label: 'Picto'
    options:
      '#required': TRUE
  image_alt:
    type: text
    label: 'Image alt'
extra_fields:
  intro:
    type: textarea
    lable: 'Introduction'
  btn_more:
    type: url_extended
    label: 'More button'
  slider:
    type: checkbox
    label: 'Show slider'

