name: '59 - Froala - CTA Social Media'
multiple: TRUE
category: 'Call to action'
enabled: TRUE
limit: 10
fields:
  link:
    type: url_extended
    label: 'Lien'
extra_fields:
  title:
      type: text
      label: 'Titre'
