name: 'D18 - Team V2'
multiple: TRUE
category: 'Teams'
enabled: TRUE
fields:
  image:
    type: image
    label: 'Image Profile'
    options:
      '#required': TRUE
  image_alt:
      type: text
      label: 'Text alternatif'
  name:
    type: text
    label: 'Name'
    options:
      '#required': TRUE
  role:
    type: text
    label: 'Role'
extra_fields:
  title:
      type: text
      label: 'Titre'
