name: "C32 - Push Text par dessus l'image"
multiple: TRUE
category: 'Content'
enabled: TRUE
fields:
  image:
    type: image
    label: 'Thumbnail'
    options:
      '#required': TRUE
  titre:
    type: text
    label: 'Titre'
    options:
      '#required': TRUE
  description:
    type: textarea
    label: 'Description'
  link:
    type: url_extended
    label: 'Lien'
  mode:
    type: checkbox
    label: "Afficher l'image en Full"
