name: '88 - Froala - Features 4 Blocks Image Title & CTA'
multiple: TRUE
category: 'Froala'
enabled: TRUE
limit: 4
fields:
  image:
    type: image
    label: 'Image'
  image_alt:
    type: text
    label: 'Text alternatif'
  title:
    type: text
    label: 'Titre'
  link:
    type: url_extended
    label: 'Lien'
