name: 'DF: Testimonials image, description & name'
multiple: TRUE
category: 'Testimonials'
enabled: TRUE
fields:
  description:
    type: textarea
    label: 'Description'
  name:
    type: text
    label: 'Name'
    options:
      '#required': TRUE
  role:
    type: text
    label: 'Role'
  image:
    type: image
    label: 'Image Profile'
    options:
      '#required': TRUE
  image_alt:
      type: text
      label: 'Text alternatif'
extra_fields:
  intro:
    type: textarea
    label: 'Introduction'
  mode:
    type: checkbox
    label: 'Active reverse mode'
  slideToShowTablet:
    type: number
    label: 'how many slide to show in tablet view'
    options:
      '#required': TRUE
  slideToShowDesktop:
    type: number
    label: 'how many slide to show in desktop view'
    options:
      '#required': TRUE
