name: 'D30 - Features blocks'
multiple: TRUE
category: 'Content'
enabled: TRUE
fields:
  image:
    type: image
    label: 'Picto'
  image_alt:
      type: text
      label: 'Text alternatif'
  title:
    type: text
    label: 'Titre'
  description:
    type: textarea
    label: 'Description'
  link:
    type: url_extended
    label: 'Lien'
