name: 'Three Columns'
multiple: FALSE
category: 'News'
enabled: TRUE
fields:
  title:
    type: text
    label: "Titre"
  description:
    type: text_format
    label: 'Description'
    options:
      '#format': 'basic_html'
  views:
    type: dynamic_views
    label: 'Views'
    options:
      '#required': TRUE
      '#default_value':
        views_id: vactory_news
        views_display_id: block_three_columns
        fields:
          - id
          - uuid
          - title
          - url
          - field_vactory_excerpt
          - field_vactory_date
          - field_vactory_news_theme
          - field_vactory_media
  link:
    type: url_extended
    label: 'Lien'
