name: '7 - Froala - Content Title, Sub-title, CTA & Fluid Image'
multiple: FALSE
category: 'Froala'
enabled: TRUE
fields:
  title:
    type: text
    label: 'Titre'
  subtitle:
    type: text
    label: 'Sub-Title'
  link_1:
    type: url_extended
    label: 'Link 1'
  link_2:
    type: url_extended
    label: 'Link 2'
  image:
    type: image
    label: 'Fluid Image'
  image_alt:
    type: text
    label: 'Text alternatif'
