name: '72 - Froala - CTA Inline Title & Description, With Image Fluid'
multiple: FALSE
category: 'Froala'
enabled: TRUE
fields:
  title:
    type: text
    label: 'Titre'
  description:
    type: text_format
    label: 'Description'
    options:
      '#format': 'full_html'
  link:
    type: url_extended
    label: 'Lien'
  image:
    type: image
    label: 'Image'
  image_alt:
     type: text
     label: 'Text alternatif'
