name: 'D01 - Jumbotron'
multiple: FALSE
category: 'Content'
enabled: TRUE
fields:
  title:
      type: text
      label: 'Title'
  description:
        type: textarea
        label: 'Description'
  label:
        type: textarea
        label: 'label Text'
  link:
      type: url_extended
      label: 'Read More Link'
