name: 'C09 - 3 boutons'
multiple: TRUE
category: 'Call to action'
limit: 3
enabled: TRUE
fields:
  title:
    type: text
    label: 'Title'
    options:
      '#required': TRUE
  link:
    type: url_extended
    label: 'Lien du bouton'
    options:
      '#requited': TRUE