name: '22 - Froala - Content Left Block Text, CTA & Follow US With Background'
multiple: TRUE
category: 'Call to action'
enabled: TRUE
fields:
  link:
    type: url_extended
    label: 'Titre Social Network'
extra_fields:
  image:
    type: image
    label: 'Background'
    options:
      '#required': TRUE
  title:
    type: text
    label: 'Titre'
  description:
    type: textarea
    label: 'Description'
  link:
    type: url_extended
    label: 'Lien'
  mode:
    type: checkbox
    label: 'Activer le mode inversé'