name: 'S08 - Slider content avec background'
multiple: TRUE
category: 'Sliders'
enabled: TRUE
fields:
  title:
    type: text
    label: 'Titre'
    options:
      '#required': TRUE
  description:
    type: textarea
    label: 'Description'
    options:
      '#required': TRUE
  link:
    type: url_extended
    label: 'Lien'
    placeholder_value: 'https://www.google.com'
    options:
      '#required': TRUE
extra_fields:
  weight: 999
  image:
    type: image
    label: 'background'
    options:
      '#required': TRUE
  group_gonfig:
    g_title: 'Configuration Slider'
    arrows:
      type: checkbox
      label: 'Afficher buttons de navigation'
    dots:
      type: checkbox
      label: 'Afficher paginations'
      options:
        '#checked': 'checked'
    autoLoop:
      type: checkbox
      label: 'Auto Slide'
    loopSpeed:
      type: number
      label: 'Slide Speed'
