vactory_otp.settings:
  type: config_object
  label: 'Vactory OTP settings'
  mapping:
    from:
      type: text
      label: "From"
    url:
      type: text
      label: 'Url'
    api_key:
      type: text
      label: 'Api key'
    default_sms_body:
      type: text
      label: 'SMS body'
    default_mail_body:
      type: text_format
      label: 'Email body'
