name: 'List'
multiple: FALSE
category: 'News'
enabled: TRUE
fields:
  views:
    type: dynamic_views
    label: 'Views'
    options:
      '#required': TRUE
      '#default_value':
        views_id: vactory_news
        views_display_id: block_list
        fields:
          - id
          - uuid
          - title
          - url
          - field_vactory_excerpt
          - field_vactory_date
          - field_vactory_news_theme
          - field_vactory_media
        vocabularies:
          vactory_news_theme: vactory_news_theme
