name: 'Header - Variant 2'
multiple: TRUE
category: 'Headers'
enabled: TRUE
extra_fields:
  header_logo:
      type: image
      label: "Header's logo"
  show_language_dropdown:
      type: checkbox
      label: "Display language dropdown"
  show_account:
      type: checkbox
      label: "Enable account button"
  use_menu:
      type: text
      label: "Menu Main ID"
      options:
        '#description': 'Menu machine name. Default to main'
