vactory_quiz_certificat.settings:
  type: config_object
  label: 'Vactory Quiz Certificat Settings'
  mapping:
    certificat_body:
      type: mapping
      label: Notifications
      mapping:
        value:
          type: text
          label: "Certificat Body"
